config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :votes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",  :registrations => "registrations" }
  resources :users
  resources :comments
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :comments
  has_many :votes

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
      devise_parameter_sanitizer.for(:sign_up) << :mvp
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  def edit_comment
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to current_user, notice: 'Bingo, Bango, Bongo! You are registered for the PG Time Machine' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to current_user, notice: 'Successfully Updated Dud!' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Registration was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :bus, :mvp, :payment)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@comments = Comment.all.order("id DESC")
  	@mvps = User.where("mvp = 1")
  	@votes = Vote.all
  	@users = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_comment_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      redirect_to new_comment_path , notice: 'Signed in successfully.'
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    @registrations = User.all.order("id DESC")
    @comment = Comment.find_by(:user_id => current_user)

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @users = User.where("mvp = 1")
    @vote = current_user.votes.build
  end

  # GET /votes/1/edit
  def edit
    @users = User.where("mvp = 1")
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = current_user.votes.build(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:mvp_id, :user_id, :vote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_form.html.erb
<!-- Content
    ============================================= -->
    <section id="content">

      <div class="content-wrap">

        <div class="container clearfix">

          <% if Comment.exists?(:user_id => current_user.id) %>
  
                  <h3>You are already registered for #pgtimemachine. What would you like to do now?</h3>
                  <h2><%= link_to "Go to the homepage", root_path %></h2>
                  <h2><%= link_to "Go to my account", current_user %></h2>
                  <h2><a href="http://www.youtuberandomvideo.com/" target="_blank">Watch a random YouTube video<a/></h2>
              <% else %>


          <div class="tabs divcenter nobottommargin clearfix" id="tab-login-register" style="max-width: 500px;">
                
                        <div class="tab-container">

                            <div class="tab-content clearfix" id="tab-login">
                                <div class="panel panel-default nobottommargin">
                                  <div class="panel-body" style="padding: 40px;">

                                    <%= form_for(@comment) do |f| %>
                                      <% if @comment.errors.any? %>
                                        <div id="error_explanation">
                                          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                                          <ul>
                                          <% @comment.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                          <% end %>
                                          </ul>
                                        </div>
                                      <% end %>

                                      <h3>One more quick thing</h3>

                                      <div class="col_full">
                                          <%= f.label :mvp, "Who would you like to nominate for MVP?" %>
                                          <%= f.text_field :mvp, :class => "form-control", :placeholder => "EX: Nate Andorsky (Big Boss)" %>
                                          <%= f.hidden_field :payment, :value => "Not Paid" %>
                                      </div>

                                      <div class="col_full">
                                          <%= f.label :bus, "Will you be participating in the bus transportation?" %>


                                          <%= f.label :bus, "Yes"  %>
                                          <%= f.radio_button :bus, "Yes" %>
                                          <%= f.label :bus, "No" %>
                                          <%= f.radio_button :bus, "No" %>

                                      </div>

                                      <% if current_user.provider == "facebook" %>
                                      <div class="col_full">
                                          <%= f.label :comment, "Leave a comment for the homepage (optional)" %><br>
                                          <em>This comment will be shown on the homepage along with your Facbeook photo.</em>
                                          <%= f.text_area :comment, :maxlength => 140, :class => "form-control", :placeholder => "so pumped for this! Cannot wait!" %>
                                          <em>Limit of 140 characters.</em>
                                      </div>
                                      <% end %>

                                      <div class="col_full nobottommargin">
                                          <%= f.submit "Complete Registration", :class => "button button-3d button-black nomargin",  data: { disable_with: "Completing..." } %>
                                      </div>

                                  <% end %>
                                  </div>
                                </div>
                            </div>

                        </div>

                    </div>
                  <% end %>
        </div>

      </div>

    </section><!-- #content end -->

app/views/comments/edit.html.erb
<!-- Content
    ============================================= -->
    <section id="content">

      <div class="content-wrap">

        <div class="container clearfix">

          <div class="tabs divcenter nobottommargin clearfix" id="tab-login-register" style="max-width: 500px;">
                
                        <div class="tab-container">

                            <div class="tab-content clearfix" id="tab-login">
                                <div class="panel panel-default nobottommargin">
                                  <div class="panel-body" style="padding: 40px;">

                                    <%= form_for(@comment) do |f| %>
                                      <% if @comment.errors.any? %>
                                        <div id="error_explanation">
                                          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                                          <ul>
                                          <% @comment.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                          <% end %>
                                          </ul>
                                        </div>
                                      <% end %>

                                      <h3>Payment for <%= @comment.user.name %></h3>
                                      <h3>Payment Status: <%= @comment.payment %></h3>

                                      <div class="col_full">
                                          <%= f.check_box :payment, {:class => "form-contorl"}, "Paid", "Not Paid" %>
                                          <%= f.label :payment, "Paid" %>
                                      </div>

                                      <div class="col_full nobottommargin">
                                          <%= f.submit "Update", :class => "button button-3d button-black nomargin",  data: { disable_with: "Updating..." } %>
                                      </div>

                                  <% end %>
                                  </div>
                                </div>
                            </div>

                        </div>

                    </div>
        </div>

      </div>

    </section><!-- #content end -->

app/views/comments/edit_comment.html.erb
<!-- Content
    ============================================= -->
    <section id="content">

      <div class="content-wrap">

        <div class="container clearfix">


          <div class="tabs divcenter nobottommargin clearfix" id="tab-login-register" style="max-width: 500px;">
                
                        <div class="tab-container">

                            <div class="tab-content clearfix" id="tab-login">
                                <div class="panel panel-default nobottommargin">
                                  <div class="panel-body" style="padding: 40px;">

                                    <%= form_for(@comment) do |f| %>
                                      <% if @comment.errors.any? %>
                                        <div id="error_explanation">
                                          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                                          <ul>
                                          <% @comment.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                          <% end %>
                                          </ul>
                                        </div>
                                      <% end %>

                                      <h3>One more quick thing</h3>

                                      <div class="col_full">
                                          <%= f.label :mvp, "Who would you like to nominate for MVP?" %>
                                          <%= f.text_field :mvp, :class => "form-control", :placeholder => "EX: Nate Andorsky (Big Boss)" %>
                                          <%= f.hidden_field :payment, :value => "Not Paid" %>
                                      </div>

                                      <div class="col_full">
                                          <%= f.label :bus, "Will you be participating in the bus transportation?" %>
                                          <%= f.select :bus, options_for_select([["Yes","Yes"],["No","No"]],''), :class => "form-control" %>
                                      </div>

                                      <% if current_user.provider == "facebook" %>
                                      <div class="col_full">
                                          <%= f.label :comment, "Leave a comment for the homepage (optional)" %><br>
                                          <em>This comment will be shown on the homepage along with your Facbeook photo.</em>
                                          <%= f.text_area :comment, :maxlength => 140, :class => "form-control", :placeholder => "so pumped for this! Cannot wait!" %>
                                          <em>Limit of 140 characters.</em>
                                      </div>
                                      <% end %>

                                      <div class="col_full nobottommargin">
                                          <%= f.submit "Complete Registration", :class => "button button-3d button-black nomargin",  data: { disable_with: "Completing..." } %>
                                      </div>

                                  <% end %>
                                  </div>
                                </div>
                            </div>

                        </div>

                    </div>
  
        </div>

      </div>

    </section><!-- #content end -->

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registration Summary:</strong><br>
  Comment: <%= @comment.comment %><br>
  MVP Nomination: <%= @comment.mvp %><br>
  Bus: <%= @comment.bus %>
</p>
Click below to Pay Kevin Meehan<br>
<a class="venmo-pay-button" data-recipient-id="1168098832941056231" data-amount="52"></a><br>
<%= link_to 'Go Back To Homepage', root_path %> 

app/views/layouts/_footer.html.erb
 <!-- Footer
        ============================================= -->
        <footer id="footer" class="dark">

            <!-- Copyrights
            ============================================= -->
            <div id="copyrights">

                <div class="container clearfix">

                    <div class="col_half">
                        2016 PG Time Machine<br><br>

                        This bad ass mo fo site was brought to you by Nate Andorsky.
                    </div>

                    <div class="col_half col_last tright">
                        <!--<div class="copyrights-menu copyright-links fright clearfix">
                            <a href="#">Home</a>/<a href="#">About</a>/<a href="#">Features</a>/<a href="#">Portfolio</a>/<a href="#">FAQs</a>/<a href="#">Contact</a>
                        </div>-->
                        
                    </div>

                </div>

            </div><!-- #copyrights end -->

        </footer><!-- #footer end -->

app/views/layouts/_header.html.erb
    <!-- Header
        ============================================= -->
        <header id="header" class="full-header">

            <div id="header-wrap">

                <div class="container clearfix">

                    <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                    <!-- Logo
                    ============================================= -->
                    <div id="logo">
                        <a href="<%= root_path %>" class="standard-logo"><!--<%= image_tag("logo-side.png") %>--></a>
                        <a href="index.html" class="retina-logo" >
                          <!--<%= image_tag("logo@2x.png") %>-->
                        </a>
                    </div><!-- #logo end -->

                    <!-- Primary Navigation
                    ============================================= -->
                    <nav id="primary-menu">
                    <% if user_signed_in? %>
                        <ul>
                            <li><%= link_to "Home", root_path %></li>
                            <li><a href="<%= root_path %>#schedule">Schedule</a></li>
                            <li><a href="<%= root_path %>#social">Social</a></li>
                            <li><a href="<%= root_path %>#mvp">MVPs</a></li>
                            <li><%= link_to "My Account", current_user %></li>
                            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>                            
                        </ul>
                    <% else %>
                          <ul>
                            <li><%= link_to "Home", root_path %></li>
                            <li><a href="<%= root_path %>#schedule">Schedule</a></li>
                            <li><a href="<%= root_path %>#social">Social</a></li>
                            <li><a href="<%= root_path %>#mvp">MVPs</a></li>
                            <li><%= link_to "Register", new_user_registration_path %></li>
                            <li><%= link_to "Sign in", new_user_session_path %></li>
                        </ul>
                    <% end %>

                    </nav>
                </div>
            </div>

    </header>


 

app/views/pages/home.html.erb
<script type="text/javascript" src="path/to/instafeed.min.js"></script>


<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'sophistinate',
        clientId: 'c8933bfc424d4012b549292c92538c41'
        accessToken: '232366354.1677ed0.b7901f96e29144128fe758ac31702e03'
    });
    feed.run();
</script>


<div id="instafeed"></div>

app/views/users/show.html.erb
<!-- Page Title
    ============================================= -->
    <section id="page-title">

      <div class="container clearfix">
        <h1>My Account</h1>
      </div>

    </section><!-- #page-title end -->


 <section id="content">

            <div class="content-wrap">


          <% flash.each do |name, msg| %>
            <div class="container clearfix">
              <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong><%= content_tag(:div, msg) %></strong> 
                
                <% if @comment.bus == "Yes" %>
                Since you will be riding the bus, to pay via venmo <a href="https://venmo.com/?txn=pay&recipients=Kevin-Meehan-1&amount=10.00&note=PGTM-Bus&" target="_blank">click here</a>.
                <% end %>
              </div>
            </div>
            <% end %>

                <div class="container clearfix">
                  <div class="heading-block title-center nobottomborder">
                    <h2>2016 PG Time Machine Countdown</h2>
                </div>

                  <div id="countdown-ex1" class="countdown countdown-large coming-soon divcenter bottommargin" style="max-width:700px;"></div>

                <script>
                    jQuery(document).ready( function($){
                        var newDate = new Date(2016, 3, 30);
                        $('#countdown-ex1').countdown({until: newDate});
                    });
                </script>


                    <!-- Post Content
                    ============================================= -->
                    <div class="postcontent nobottommargin clearfix">
                    	
                    	<div class="table-responsive">

                            <div class="table-responsive">
                          <table class="table">
                            <tbody>
                              <tr>
                                <td>Name</td>
                                <td><%= current_user.name %></td>
                              </tr>
                             <tr>
                                <td>Email</td>
                                <td><%= current_user.email %></td>
                              </tr>
                              <tr>
                                <td>MVP Nomiation</td>
                                <td><%= @comment.mvp %></td>
                              </tr>
                              <tr>
                                <td>Bus</td>
                                <td>
                                  <% if @comment.bus == "Yes" %><br>
                                    <% if @comment.payment == "Not Paid" %>
                                      Since you will be riding the bus, to pay via venmo <a href="https://venmo.com/?txn=pay&recipients=Kevin-Meehan-1&amount=10.00&note=PGTM-Bus&" target="_blank">click here</a><br>
                                    <a class="btn btn-sm btn-danger">Not Paid</a>
                                    <% else %>
                                    <a class="btn btn-sm btn-success">Paid</a>
                                    <% end %>
                                  <% else %>
                                    Not riding the bus
                                  <% end %>
                                </td>
                              </tr>
                          <% if current_user.provider == "facebook" %>    
                              <tr>
                                <td>Comment for the homepage</td>
                                <td><div class="testi-content"><p><%= @comment.comment %></p></div></td>
                              </tr>
                          <% end %>
                            </tbody>
                          </table>
                        

                        </div>

                          </div>


                    </div>

                </div>

            </div>

  </section>

<% if current_user.mvp == 2 %>
        <section id="content">

            <div class="content-wrap">

                <div class="container clearfix">

                    <!-- Post Content
                    ============================================= -->
                    
                        <h4>Registrations - <%= @registrations.count %></h4>
                        <table class="table table-striped">
                          <thead>
                            <tr>
                              <th>Date</th>
                              <th>Name</th>
                              <th width="80px;">Email</th>
                              <th>Bus</th>
                              <th width="80px;">Payment</th>
                              <th>MVP</th>
                              <th>Comment</th>

                            </tr>
                          </thead>
                          <tbody>
                          <% @registrations.each do |user| %>
                                  <tr>
                                    <td><%= user.created_at.strftime("%b %d at %l:%M %p") %></td>
                                    <td><%= user.name %></td>
                                    <td><%= user.email %></td>
                                    <td><%= Comment.find_by(:user_id => user).try(:bus) %></td>
                                    <% if Comment.find_by(:user_id => user).try(:bus) == "Yes" %>

                                        <% if Comment.find_by(:user_id => user).try(:payment) == "Paid" %>
                                        <td><label class="label label-success">Yes</label><a href="<%= edit_comment_path(Comment.find_by(:user_id => user)) %>">  <i class="icon-pencil2"></i></a></td>
                                        <% else %>
                                        <td><label class="label label-danger">No</label><a href="<%= edit_comment_path(Comment.find_by(:user_id => user)) %>">  <i class="icon-pencil2"></i></a></td>
                                        <% end %>
                                    
                                    <% else %>
                                    
                                    <td><label class="label label-default">N-A</label></td>
                                    
                                    <% end %>
                                    
                                    <td><%= Comment.find_by(:user_id => user).try(:mvp) %></td>
                                    <td><%= Comment.find_by(:user_id => user).try(:comment) %></td>
                                  </tr>
                            <% end %>
                          </tbody>
                        </table>

                     
                    </div>
                  </div>
          </section>

<% end %>

<section id="content">

            <div class="content-wrap">

                <div class="container clearfix">

                    <!-- Post Content
                    ============================================= -->
                    
                        <h4>PG Time Machine 2016 Roster</h4>
                        <table class="table table-striped">
                          <thead>
                            <tr>
                              <th>Name</th>
                            </tr>
                          </thead>
                          <tbody>
                          <% @registrations.each do |user| %>
                                  <tr>
                                    <td><%= user.name %></td>
                                  </tr>
                            <% end %>
                          </tbody>
                        </table>

                     
                    </div>
                  </div>
          </section>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Mvp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.mvp_id %></td>
        <td><%= vote.user_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>MVP Vote:</strong>
  <%= User.find(@vote.mvp_id).name %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>